"""program_management 场景 6 专科书库 (软件工程真实经典 + 实务).

dept_id: principal_architect / senior_engineer / frontend_engineer /
         dba / security_engineer / qa_engineer
roles: helper=查阅/工具, attending=常规实现, reviewer=风险/审查.
"""
from __future__ import annotations

from .engine import (
    Book, SpecialtyLibrary,
    ROLE_HELPER, ROLE_ATTENDING, ROLE_REVIEWER, ALL_ROLES,
)

H = (ROLE_HELPER,)
A = (ROLE_ATTENDING,)
R = (ROLE_REVIEWER,)
HA = (ROLE_HELPER, ROLE_ATTENDING)
AR = (ROLE_ATTENDING, ROLE_REVIEWER)


def _b(title, author, core, roles=None, layer="book", imp=4):
    return Book(title=title, author=author, core=core, roles=roles or ALL_ROLES, layer=layer, importance=imp)


principal_architect = SpecialtyLibrary("principal_architect", "首席架构师", [
    _b("设计数据密集型应用(DDIA)", "Kleppmann", "存储引擎/复制/分区/事务/一致性/批流; 分布式系统圣经。", imp=5),
    _b("架构整洁之道", "Robert Martin", "SOLID、依赖倒置、边界、用例驱动、框架无关。", imp=5),
    _b("企业应用架构模式(PoEAA)", "Martin Fowler", "分层、领域模型、数据映射、并发、分布式模式。", roles=AR, imp=5),
    _b("领域驱动设计(DDD)", "Eric Evans", "限界上下文、聚合、通用语言、复杂业务建模。", roles=A, imp=5),
    _b("微服务架构设计模式", "Chris Richardson", "服务拆分、Saga、CQRS、API组合、分布式事务。", roles=AR, imp=5),
    _b("系统设计面试", "Alex Xu", "可扩展系统模板: 限流/缓存/分片/一致性哈希/CDN。", roles=HA, imp=5),
    _b("Release It! 发布", "Michael Nygard", "稳定性模式: 断路器/舱壁/超时/限流; 容量。", roles=AR, imp=4),
    _b("软件架构基础", "Mark Richards", "架构特性、风格、权衡分析、架构决策。", roles=A, imp=4),
    _b("凤凰架构", "周志明", "从单体到云原生、分布式、服务网格、可观测。", roles=A, imp=4),
    _b("人月神话", "布鲁克斯", "加人不快、概念完整性、没有银弹。", roles=A, imp=4),
    _b("数据库系统概念", "Silberschatz", "关系模型、事务、并发、恢复; 数据库理论。", roles=A, imp=4),
    _b("可扩展性与高并发", "实务专著", "水平扩展、缓存、消息队列、读写分离、分库分表。", roles=A, imp=5),
    _b("一致性与CAP", "实务专著", "CAP/BASE、最终一致、分布式共识(Raft/Paxos)。", roles=AR, imp=4),
    _b("缓存架构", "实务专著", "多级缓存、击穿/穿透/雪崩、一致性、热点。", roles=A, imp=4),
    _b("消息队列与事件驱动", "实务专著", "Kafka/RabbitMQ、解耦、削峰、顺序、幂等。", roles=A, imp=4),
    _b("API与接口设计", "实务专著", "RESTful/GraphQL/gRPC、版本、幂等、限流。", roles=A, imp=4),
    _b("高可用与容灾", "实务专著", "多活、故障转移、降级熔断、SLA、混沌工程。", roles=AR, imp=4),
    _b("技术选型与权衡", "实务专著", "选型框架、成熟度、团队匹配、避免炫技。", roles=AR, imp=5),
    _b("架构决策记录(ADR)", "实务工具", "记录架构决策、背景、权衡、后果。", roles=H, imp=4),
    _b("云原生与K8s架构", "实务专著", "容器、编排、服务网格、Serverless、成本。", roles=A, imp=4),
    _b("可观测性架构", "实务专著", "日志/指标/链路、SLO、告警、根因分析。", roles=A, imp=4),
    _b("数据架构与中台", "实务专著", "数仓、湖仓、实时数仓、数据治理。", roles=A, imp=3),
    _b("性能与容量规划", "实务专著", "压测、容量评估、瓶颈、成本。", roles=AR, imp=4),
    _b("安全架构设计", "实务专著", "零信任、纵深防御、认证授权、加密。", roles=R, imp=4),
    _b("演进式架构", "实务专著", "适应度函数、增量演进、避免大爆炸重写。", roles=A, imp=4),
    _b("分布式系统陷阱", "实务专著", "八大谬误、网络不可靠、时钟、部分失败。", roles=R, imp=5),
    _b("过度设计与YAGNI", "实务专著", "别为想象规模过度设计、够用、按需演进。", roles=R, imp=5),
    _b("技术债与重构策略", "实务专著", "技术债量化、偿还、绞杀者模式。", roles=R, imp=4),
    _b("成本与架构权衡", "实务专著", "云成本、性能/成本/可靠性三角权衡。", roles=R, imp=4),
    _b("架构评审清单", "实务工具", "扩展性/可用性/安全/成本/可维护性评审。", roles=R, imp=4),
])

senior_engineer = SpecialtyLibrary("senior_engineer", "资深工程师", [
    _b("代码整洁之道(Clean Code)", "Robert Martin", "命名、函数、注释、格式、错误处理、可读性。", imp=5),
    _b("重构(Refactoring)", "Martin Fowler", "代码坏味道、重构手法、测试保护下的小步改进。", imp=5),
    _b("程序员修炼之道", "Hunt/Thomas", "DRY、正交、曳光弹、契约、实用主义。", imp=5),
    _b("代码大全(Code Complete)", "Steve McConnell", "设计/编码/调试/测试/质量全景。", roles=AR, imp=5),
    _b("算法导论(CLRS)", "Cormen 等", "算法与数据结构权威; 复杂度、排序、图、DP。", roles=AR, imp=4),
    _b("算法(Algorithms)", "Sedgewick", "实用算法实现、数据结构、图、字符串。", roles=H, imp=4),
    _b("Effective 系列", "各语言专著", "语言最佳实践条目、惯用法、陷阱。", roles=HA, imp=5),
    _b("设计模式(GoF)", "四人帮", "23种经典模式、创建/结构/行为型。", roles=A, imp=4),
    _b("修改代码的艺术", "Michael Feathers", "为遗留代码加测试、解依赖、安全修改。", roles=AR, imp=4),
    _b("调试九法", "David Agans", "系统化调试: 理解系统、制造失败、分而治之。", roles=AR, imp=4),
    _b("复杂度分析与性能", "实务专著", "时间空间复杂度、热点、优化、profiling。", roles=A, imp=4),
    _b("并发编程", "实务专著", "线程/协程、锁、无锁、内存模型、死锁。", roles=AR, imp=4),
    _b("错误处理与健壮性", "实务专著", "异常、错误码、防御式编程、失败处理。", roles=R, imp=5),
    _b("可维护性与可读性", "实务专著", "命名、模块化、低耦合高内聚、复杂度控制。", roles=A, imp=5),
    _b("工时估算", "实务专著", "拆解、不确定性、缓冲、避免乐观估计。", roles=AR, imp=4),
    _b("代码评审实践", "实务专著", "评审清单、建设性反馈、自动化检查。", roles=A, imp=4),
    _b("单元测试与TDD", "实务专著", "测试先行、可测性、mock、覆盖率。", roles=A, imp=4),
    _b("版本控制与Git", "实务工具", "分支策略、提交规范、冲突、回滚。", roles=H, imp=4),
    _b("API与库的使用", "实务工具", "文档查阅、版本兼容、依赖管理。", roles=H, imp=3),
    _b("函数式与不可变", "实务专著", "纯函数、不可变、副作用隔离。", roles=A, imp=3),
    _b("领域建模与抽象", "实务专著", "恰当抽象、避免过度抽象、贴近业务。", roles=A, imp=4),
    _b("日志与调试技巧", "实务专著", "有效日志、断点、二分定位、最小复现。", roles=H, imp=4),
    _b("代码坏味道清单", "实务工具", "长函数/重复/过大类/深嵌套等坏味道。", roles=R, imp=4),
    _b("依赖管理与解耦", "实务专著", "依赖注入、接口隔离、降低耦合。", roles=A, imp=4),
    _b("性能优化实战", "实务专著", "瓶颈定位、缓存、批处理、I/O优化。", roles=A, imp=4),
    _b("可测试性设计", "实务专著", "纯逻辑分离、依赖抽象、可注入。", roles=A, imp=3),
    _b("技术文档写作", "实务工具", "README、设计文档、注释、知识沉淀。", roles=H, imp=3),
    _b("过早优化陷阱", "实务专著", "先正确再优化、别猜瓶颈、用数据。", roles=R, imp=4),
    _b("实现路径与方案对比", "实务专著", "多方案权衡、复杂度、可维护性、工时。", roles=AR, imp=4),
    _b("复杂度与认知负荷", "实务专著", "降低认知负荷、简单优先、KISS。", roles=R, imp=4),
])

frontend_engineer = SpecialtyLibrary("frontend_engineer", "前端工程师", [
    _b("JavaScript高级程序设计(红宝书)", "Nicholas Zakas", "JS语言核心、DOM、事件、异步、模块。", roles=HA, imp=5),
    _b("你不知道的JavaScript", "Kyle Simpson", "作用域闭包、this、原型、类型、异步。", roles=A, imp=4),
    _b("CSS世界/CSS揭秘", "张鑫旭/Lea Verou", "布局、盒模型、Flex/Grid、动画、技巧。", roles=HA, imp=4),
    _b("React设计原理", "专著", "组件、状态、Hooks、虚拟DOM、Fiber、调和。", roles=A, imp=4),
    _b("Vue.js设计与实现", "霍春阳", "响应式、虚拟DOM、编译、组件化原理。", roles=A, imp=4),
    _b("Web性能权威指南", "Ilya Grigorik", "网络、加载、渲染、性能优化底层。", roles=AR, imp=5),
    _b("前端性能优化", "实务专著", "首屏、懒加载、代码分割、缓存、CDN、Core Web Vitals。", roles=AR, imp=5),
    _b("Web无障碍(Accessibility)", "实务专著", "WCAG、语义化、ARIA、键盘、屏幕阅读器。", roles=R, imp=4),
    _b("状态管理", "实务专著", "Redux/Zustand、单向数据流、避免过度全局化。", roles=A, imp=4),
    _b("响应式与移动适配", "实务专著", "媒体查询、rem/vw、移动端、触控。", roles=A, imp=4),
    _b("TypeScript类型体操", "实务专著", "类型系统、泛型、推断、类型安全。", roles=A, imp=4),
    _b("浏览器工作原理", "实务专著", "渲染流程、重排重绘、事件循环、内存。", roles=AR, imp=4),
    _b("前端工程化", "实务专著", "构建(Webpack/Vite)、模块化、CI、Monorepo。", roles=A, imp=4),
    _b("交互设计与UX(前端)", "实务专著", "用户体验、交互反馈、加载状态、空态。", roles=A, imp=4),
    _b("组件库与设计系统", "实务专著", "组件抽象、Design Token、可复用、文档。", roles=A, imp=4),
    _b("Web安全(前端)", "实务专著", "XSS/CSRF、CSP、同源、Cookie安全。", roles=R, imp=5),
    _b("动画与视觉", "实务专著", "CSS动画、rAF、性能、流畅。", roles=A, imp=3),
    _b("跨端与小程序", "实务专著", "小程序、RN/Flutter、跨端方案权衡。", roles=A, imp=3),
    _b("前端测试", "实务专著", "单元/组件/E2E、Jest/Testing Library/Cypress。", roles=A, imp=4),
    _b("PWA与离线", "实务专著", "Service Worker、缓存、离线、推送。", roles=H, imp=3),
    _b("可访问性审计", "实务工具", "对比度、焦点、语义、读屏测试。", roles=R, imp=4),
    _b("首屏与渲染优化", "实务专著", "SSR/SSG、骨架屏、预加载、关键渲染路径。", roles=A, imp=4),
    _b("前端监控与异常", "实务专著", "错误上报、性能监控、用户行为埋点。", roles=H, imp=3),
    _b("CSS架构与命名", "实务专著", "BEM、原子化(Tailwind)、CSS-in-JS、可维护。", roles=A, imp=3),
    _b("浏览器兼容性", "实务专著", "Polyfill、降级、特性检测、Can I Use。", roles=H, imp=3),
    _b("大型前端项目组织", "实务专著", "目录结构、模块边界、状态分层。", roles=A, imp=3),
    _b("用户体验细节", "实务专著", "防抖节流、乐观更新、错误友好提示。", roles=A, imp=4),
    _b("前端性能指标", "实务工具", "LCP/FID/CLS/TTI、Lighthouse、监控。", roles=H, imp=4),
    _b("过度设计与体验平衡", "实务专著", "炫技vs可用、动画克制、性能优先。", roles=R, imp=3),
    _b("可维护的前端架构", "实务专著", "组件化、关注分离、避免巨型组件。", roles=A, imp=4),
])

dba = SpecialtyLibrary("dba", "DBA / 数据架构师", [
    _b("高性能MySQL", "Baron Schwartz 等", "索引、查询优化、schema、复制、分库分表、调优。", imp=5),
    _b("数据库系统概念", "Silberschatz", "关系模型、SQL、事务、并发控制、恢复。", roles=AR, imp=5),
    _b("SQL反模式", "Bill Karwin", "常见SQL/schema设计错误与正解。", roles=R, imp=5),
    _b("数据库索引设计与优化", "Tapio Lahdenmaki", "索引原理、覆盖索引、最优索引设计。", roles=A, imp=5),
    _b("PostgreSQL修炼之道", "专著", "PG特性、索引、JSONB、分区、性能。", roles=A, imp=4),
    _b("Redis设计与实现", "黄健宏", "数据结构、持久化、复制、集群、缓存模式。", roles=A, imp=4),
    _b("数据密集型应用(DDIA)", "Kleppmann", "存储引擎、复制、分区、一致性。", roles=AR, imp=5),
    _b("schema设计与范式", "实务专著", "范式与反范式、字段类型、约束、可演进。", roles=HA, imp=5),
    _b("索引原理与优化", "实务专著", "B+树、联合索引、最左前缀、回表、索引失效。", roles=A, imp=5),
    _b("SQL查询优化", "实务专著", "执行计划、慢查询、JOIN优化、子查询。", roles=AR, imp=5),
    _b("事务与隔离级别", "实务专著", "ACID、隔离级别、锁、MVCC、死锁。", roles=AR, imp=4),
    _b("分库分表与分片", "实务专著", "水平/垂直拆分、分片键、跨片查询、扩容。", roles=A, imp=4),
    _b("读写分离与复制", "实务专著", "主从、延迟、读写分离、故障切换。", roles=A, imp=4),
    _b("数据一致性与完整性", "实务专著", "外键、约束、应用层校验、最终一致。", roles=R, imp=5),
    _b("数据库高可用", "实务专著", "主备、集群、failover、备份恢复。", roles=AR, imp=4),
    _b("缓存与数据库一致性", "实务专著", "缓存更新策略、双写、延迟双删、缓存穿透。", roles=A, imp=4),
    _b("NoSQL与选型", "实务专著", "KV/文档/列/图数据库、适用场景。", roles=A, imp=3),
    _b("时序与分析型数据库", "实务专著", "ClickHouse/时序库、OLAP vs OLTP。", roles=A, imp=3),
    _b("数据备份与恢复", "实务专著", "全量/增量、PITR、演练、RPO/RTO。", roles=R, imp=5),
    _b("数据迁移", "实务专著", "在线迁移、双写、灰度、回滚。", roles=AR, imp=4),
    _b("数据库监控与诊断", "实务工具", "慢日志、连接数、锁等待、性能视图。", roles=H, imp=4),
    _b("大数据量处理", "实务专著", "批量、分页深翻、归档、冷热分离。", roles=A, imp=4),
    _b("数据安全与脱敏", "实务专著", "权限、加密、脱敏、审计、最小授权。", roles=R, imp=5),
    _b("连接池与资源", "实务专著", "连接池配置、连接泄漏、资源限制。", roles=A, imp=3),
    _b("数据建模(OLAP)", "实务专著", "星型/雪花、维度建模、数仓分层。", roles=A, imp=3),
    _b("SQL注入防护", "实务专著", "参数化、预编译、最小权限、ORM安全。", roles=R, imp=5),
    _b("数据库版本管理", "实务工具", "migration、Flyway/Liquibase、变更评审。", roles=H, imp=4),
    _b("慢查询治理", "实务工具", "慢查询发现、分析、优化、监控。", roles=AR, imp=4),
    _b("数据完整性陷阱", "实务专著", "并发更新、丢失更新、脏读、约束缺失。", roles=R, imp=5),
    _b("数据库选型与权衡", "实务专著", "关系vs NoSQL、自建vs云、成本与运维。", roles=AR, imp=4),
])

security_engineer = SpecialtyLibrary("security_engineer", "安全工程师", [
    _b("白帽子讲Web安全", "吴翰清", "Web安全体系、XSS/CSRF/注入、认证授权、防御。", imp=5),
    _b("Web应用安全权威指南", "专著", "OWASP、漏洞原理、攻防、安全开发。", roles=AR, imp=5),
    _b("OWASP Top 10", "OWASP", "注入/失效认证/敏感数据/失效访问控制等十大风险。", roles=AR, layer="standard", imp=5),
    _b("黑客攻防技术宝典(Web)", "专著", "Web渗透、漏洞利用、攻击链。", roles=A, imp=4),
    _b("应用密码学", "Bruce Schneier", "对称/非对称、哈希、签名、TLS、密钥管理。", roles=AR, imp=5),
    _b("SQL注入攻防", "实务专著", "注入原理、参数化、预编译、WAF。", roles=R, imp=5),
    _b("XSS与CSRF防护", "实务专著", "存储/反射/DOM型XSS、CSP、Token防CSRF。", roles=R, imp=5),
    _b("认证与授权(OAuth/JWT)", "实务专著", "OAuth2/OIDC、JWT、Session、最小权限、RBAC/ABAC。", roles=AR, imp=5),
    _b("密钥与凭证管理", "实务专著", "密钥轮换、KMS、Vault、硬编码风险。", roles=R, imp=5),
    _b("数据隐私与合规(个保法)", "实务专著", "个人信息保护、数据最小化、脱敏、出境。", roles=R, layer="standard", imp=5),
    _b("访问控制设计", "实务专著", "越权(水平/垂直)、RBAC、最小权限。", roles=AR, imp=5),
    _b("安全开发生命周期(SDL)", "实务专著", "威胁建模、安全设计、代码审计、渗透。", roles=A, imp=4),
    _b("威胁建模(STRIDE)", "实务专著", "欺骗/篡改/否认/信息泄露/拒服/提权。", roles=R, imp=4),
    _b("API安全", "实务专著", "鉴权、限流、签名、防重放、参数校验。", roles=AR, imp=4),
    _b("依赖与供应链安全", "实务专著", "依赖漏洞、SCA、投毒、SBOM。", roles=R, imp=4),
    _b("日志与审计安全", "实务专著", "安全日志、审计追踪、敏感信息脱敏。", roles=A, imp=4),
    _b("纵深防御与零信任", "实务专著", "多层防御、零信任、最小信任、微隔离。", roles=A, imp=4),
    _b("常见漏洞与CVE", "实务工具", "漏洞库、CVE跟踪、补丁管理。", roles=H, imp=4),
    _b("渗透测试与红队", "实务专著", "渗透流程、工具、报告、修复闭环。", roles=A, imp=3),
    _b("安全配置与加固", "实务专著", "服务器/容器/中间件加固、默认安全。", roles=R, imp=4),
    _b("敏感数据保护", "实务专著", "加密存储、传输加密、脱敏、分级。", roles=R, imp=5),
    _b("DDoS与防护", "实务专著", "限流、清洗、CDN、弹性。", roles=A, imp=3),
    _b("移动与客户端安全", "实务专著", "加固、反调试、证书校验、本地存储。", roles=A, imp=3),
    _b("安全事件响应", "实务专著", "应急、取证、溯源、复盘、止损。", roles=R, imp=4),
    _b("代码安全审计", "实务工具", "SAST/DAST、代码审计清单、自动化扫描。", roles=R, imp=4),
    _b("社会工程与钓鱼", "实务专著", "钓鱼、社工、安全意识、内部威胁。", roles=R, imp=3),
    _b("合规与等保", "实务专著", "等保2.0、ISO27001、合规要求。", roles=R, layer="standard", imp=4),
    _b("AI/LLM安全", "实务专著", "提示注入、数据泄露、越权、模型滥用。", roles=R, imp=4),
    _b("安全左移", "实务专著", "设计与编码阶段嵌入安全、CI集成扫描。", roles=A, imp=4),
    _b("安全风险清单", "实务工具", "上线前: 鉴权/注入/密钥/越权/日志检查。", roles=R, imp=5),
])

qa_engineer = SpecialtyLibrary("qa_engineer", "QA / 测试架构师", [
    _b("Google软件测试之道", "James Whittaker", "测试分级、SET/TE、测试规模金字塔、质量文化。", imp=5),
    _b("软件测试(The Art of Software Testing)", "Glenford Myers", "测试用例设计、边界、等价类、白盒黑盒。", roles=AR, imp=5),
    _b("探索式测试", "James Bach", "启发式、会话、探索、测程管理。", roles=A, imp=4),
    _b("持续交付", "Jez Humble", "部署流水线、自动化、灰度、回滚。", roles=AR, imp=5),
    _b("单元测试的艺术", "Roy Osherove", "可维护的单测、mock/stub、TDD。", roles=A, imp=4),
    _b("测试驱动开发(TDD)", "Kent Beck", "红绿重构、测试先行、可测性设计。", roles=A, imp=4),
    _b("测试用例设计方法", "实务专著", "等价类、边界值、判定表、正交、场景法。", roles=HA, imp=5),
    _b("边界条件与异常测试", "实务专著", "边界、空值、超长、并发、异常路径。", roles=R, imp=5),
    _b("测试矩阵与覆盖", "实务专著", "功能/兼容/性能/安全矩阵、覆盖率。", roles=A, imp=4),
    _b("自动化测试框架", "实务专著", "UI/接口/单元自动化、Selenium/Playwright/Pytest。", roles=A, imp=4),
    _b("接口测试", "实务专著", "Postman、契约测试、Mock、数据驱动。", roles=A, imp=4),
    _b("性能与压力测试", "实务专著", "JMeter/Locust、并发、吞吐、瓶颈、容量。", roles=AR, imp=5),
    _b("回归测试策略", "实务专著", "回归集、用例优先级、自动化回归。", roles=A, imp=4),
    _b("缺陷管理", "实务专著", "缺陷生命周期、严重度优先级、根因。", roles=H, imp=4),
    _b("E2E与集成测试", "实务专著", "端到端、集成、契约、环境管理。", roles=A, imp=4),
    _b("测试金字塔与策略", "实务专著", "单元>集成>E2E、ROI、避免冰淇淋反模式。", roles=AR, imp=5),
    _b("兼容性测试", "实务专著", "浏览器/设备/系统/分辨率兼容。", roles=A, imp=3),
    _b("安全测试", "实务专著", "越权、注入、敏感信息、安全用例。", roles=R, imp=4),
    _b("测试数据与环境", "实务专著", "测试数据构造、环境隔离、Mock服务。", roles=H, imp=4),
    _b("混沌工程与故障注入", "实务专著", "故障注入、弹性验证、稳定性。", roles=AR, imp=3),
    _b("质量度量与质量门禁", "实务专著", "质量指标、门禁、卡点、左移。", roles=R, imp=4),
    _b("可测试性设计", "实务专著", "可观测、可控、依赖隔离、测试友好。", roles=A, imp=3),
    _b("探索性与场景测试", "实务专著", "真实场景、用户路径、边角case。", roles=A, imp=4),
    _b("CI/CD中的测试", "实务专著", "流水线测试、快速反馈、并行、稳定性。", roles=A, imp=4),
    _b("Flaky测试治理", "实务专著", "不稳定测试识别、隔离、修复。", roles=R, imp=4),
    _b("验收测试与UAT", "实务专著", "验收标准、UAT、BDD/Cucumber。", roles=A, imp=3),
    _b("移动端测试", "实务专著", "真机/云测、弱网、电量、兼容。", roles=A, imp=3),
    _b("数据正确性测试", "实务专著", "数据校验、对账、ETL测试。", roles=R, imp=4),
    _b("测试报告与质量评估", "实务工具", "测试报告、风险评估、上线建议。", roles=H, imp=3),
    _b("漏测与质量风险清单", "实务工具", "常见漏测点、风险评估、上线前checklist。", roles=R, imp=5),
])

LIBRARIES = {
    "principal_architect": principal_architect,
    "senior_engineer": senior_engineer,
    "frontend_engineer": frontend_engineer,
    "dba": dba,
    "security_engineer": security_engineer,
    "qa_engineer": qa_engineer,
}
